### PR TITLE
Manifest v3, hubspot, new styles

### PR DESCRIPTION
**Pull request by dpup**
- Chrome launched a new manifest version which is now required to push to the
  web store. This change includes necessary updates.
- Adds HubSpot as an integration.
- Updates the color scheme to match latest styles.

Screen Shot 2022-04-08 at 5 30 51 PM

### CODE REVIEW

**Review by stephyeung — APPROVED** [review]
👍  Thanks for handling the manifest updates!
Also yay updated colors 🎨

**Comment by dpup** [comment]
More styling updates following feedback from @tpalmer75 .
Screen Shot 2022-04-12 at 11 09 23 AM

**Review by stephyeung — APPROVED** [review]
✨

**Comment by dpup** [comment]
And it's been published already.

**Pull request merged**
